GET http://localhost:3003/api/blogs/
Content-Type: application/json

###
GET http://localhost:3003/api/authors/
Content-Type: application/json

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "a great book title",
    "author": "a great book author",
    "url": "greatbooks1",
    "likes": 10,
    "user": "662652fbd3600d4af9d9b038"
}
