GET http://localhost:3003/api/blogs/
Content-Type: application/json

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "url": "greatbooks1",
    "title": "a great book title",
    "author": "a great book author",
    "user": "66326855617693436c999c00",
    "likes": 10
}

###

POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlcm94MiIsImlkIjoiNjY1MzQ1ZGZiMTcwZDk5MGFmZjM5OWFiIiwiaWF0IjoxNzE2NzMzNDQ3fQ.sMA1pzONt_EtNInabrSBq6Fw-C5OzYwoRLErq2mjFE4

{
    "url": "fullstackopen",
    "title": "Learn MongoDB",
    "author": "Nenad",
    "user": "6651e2ff3abdf7806515fe83",
    "likes": 9
}

###

DELETE http://localhost:3003/api/blogs/664016bb571d1373fbd981a5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlcm94MiIsImlkIjoiNjYzMjY4NTU2MTc2OTM0MzZjOTk5YzAwIiwiaWF0IjoxNzE1NDc3ODEzfQ._pq7L2z-q7iKA6ehFhP_2G_ayug74oFG7DpZHp7_qEs
