GET http://localhost:3003/api/blogs/
Content-Type: application/json

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "url": "greatbooks1",
    "title": "a great book title",
    "author": "a great book author",
    "user": "66326855617693436c999c00",
    "likes": 10
}

###

POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlcm94MiIsImlkIjoiNjYzMjY4NTU2MTc2OTM0MzZjOTk5YzAwIiwiaWF0IjoxNzE0OTU1NzIwfQ.N5zU5B_sCGzkm9rFNm0CKnWA-vg1_8cZVui0dlw8k3w

{
    "url": "themodelhealthshow",
    "title": "Sleep Smarter",
    "author": "Shawn Stevenson",
    "user": "66326855617693436c999c00",
    "likes": 10
}

###

DELETE http://localhost:3003/api/blogs/663825e72622aef1168f5fe1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inhlcm94MiIsImlkIjoiNjYzMjY4NTU2MTc2OTM0MzZjOTk5YzAwIiwiaWF0IjoxNzE0OTU1NzIwfQ.N5zU5B_sCGzkm9rFNm0CKnWA-vg1_8cZVui0dlw8k3w
