GET http://localhost:3003/api/blogs/
Content-Type: application/json

### 
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "url": "greatbooks1",
    "title": "a great book title",
    "author": "a great book author",
    "user": "66326855617693436c999c00",
    "likes": 10
}
